[data]
kitId=1

[env:esp32]
platform = espressif32
framework = arduino
board = esp32dev
; board = esp32-s3-devkitc-1 ;Para ESP32-S3, troque esse board e descomente as flags USB:
monitor_speed = 115200

; upload_protocol = espota ;Caso use OTA
; upload_port = iikit${data.kitId}.local ;Caso use OTA

build_src_filter = +<esp0.cpp>
extra_scripts = post:lasecsimul/create_merged_bin.py

build_flags =
    -DKIT_ID=${data.kitId}
    -DKIT_HOSTNAME='"iikit${data.kitId}"'
    ; -DCONFIG_ETH_USE_OPENETH=1
    ; -DCORE_DEBUG_LEVEL=3

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit SSD1306 @ ^2.5.0
    adafruit/Adafruit GFX Library @ ^1.11.0
    adafruit/Adafruit BusIO @ ^1.16.0
    tzapu/WiFiManager @ ^2.0.0